-- Seed 25 real GSU course codes into skills table
INSERT INTO skills (name) VALUES
  ('CSC 1301 - Principles of Computer Science I'),
  ('CSC 1302 - Principles of Computer Science II'),
  ('CSC 2720 - Data Structures'),
  ('CSC 3210 - Computer Organization'),
  ('CSC 4350 - Software Engineering'),
  ('MATH 1111 - College Algebra'),
  ('MATH 2211 - Calculus I'),
  ('MATH 2212 - Calculus II'),
  ('MATH 2420 - Discrete Mathematics'),
  ('BIOL 1103 - Introductory Biology I'),
  ('BIOL 1104 - Introductory Biology II'),
  ('CHEM 1211 - Principles of Chemistry I'),
  ('CHEM 1212 - Principles of Chemistry II'),
  ('PHYS 2211 - Principles of Physics I'),
  ('PHYS 2212 - Principles of Physics II'),
  ('ACCT 2101 - Principles of Accounting I'),
  ('ACCT 2102 - Principles of Accounting II'),
  ('ECON 2105 - Principles of Macroeconomics'),
  ('ECON 2106 - Principles of Microeconomics'),
  ('MGS 3100 - Business Analysis'),
  ('ENGL 1101 - English Composition I'),
  ('ENGL 1102 - English Composition II'),
  ('PHIL 2010 - Introduction to Philosophy'),
  ('PSYC 1101 - Introduction to Psychology'),
  ('POLS 1101 - American Government')
ON CONFLICT (name) DO NOTHING;